# Generated by Django 2.2 on 2019-10-10 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_auto_20191008_1347'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('active', 'Активный'), ('closed', 'Закрыт')], default='active', max_length=10, verbose_name='Статус проекта'),
        ),
    ]
