# Generated by Django 2.2 on 2019-10-10 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_project_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='projects',
        ),
        migrations.AddField(
            model_name='task',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='webapp.Project', verbose_name='projects'),
        ),
    ]
